apiVersion: v1
kind: ConfigMap
metadata:
  name: the-map
data:
  altGreeting: <+serviceVariables.altGreeting>
  enableRisky: <+serviceVariables.enableRisky>
  DD_ENV: <+infra.connectorRef>
  Example_Secret: <+secrets.getValue("kustomize_secret_example")>
